from enum import Enum


class MessageType(Enum):
    FIRE_STATUS = "FIRE_STATUS"
    DEVICE_DOWN = "DEVICE_DOWN"
    ROUTE_UPDATE = "ROUTE_UPDATE"
    RECALCULATION_COMPLETE = "RECALCULATION_COMPLETE"
    MANUAL_TRIGGER = "MANUAL_TRIGGER"
